# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs   
name: Appium UI Tests

on:
  push:
    branches: [ "POC_AppiumJS" ]
  pull_request:
    branches: [ "POC_AppiumJS" ]

jobs:
  appium-android-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Appium
      run: npm install -g appium
    - name: Install dependencies
      run: npm install
    - name: Start Appium server
      run: appium --address 127.0.0.1 --port 4723 &

    - name: Run Appium Tests
      run: npx wdio wdio.conf.js
#     - name: Run Appium tests
#       env:
#         APK_PATH: ${{ secrets.APK_PATH }}
#       run: npm test -- --capabilities.app=$APK_PATH

