# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs   
name: Appium UI Tests

on:
  push:
    branches: [ "POC_AppiumJS" ]
  pull_request:
    branches: [ "POC_AppiumJS" ]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Set up Android environment
      run: |
        # Download and install Android SDK
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip -d android-sdk
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

        # Install necessary platform tools
        sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"

    - name: Start Appium Server
      run: appium &

    - name: Run tests on Android device
      run: |
        # Start the test
        npx wdio wdio.conf.js
#     - name: Run Appium tests
#       env:
#         APK_PATH: ${{ secrets.APK_PATH }}
#       run: npm test -- --capabilities.app=$APK_PATH

